name: SwagLabs tests python

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose test set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - correct
          - incorrect
          - price
          - all

permissions:
  contents: read
  pages: write
  id-token: write
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run autotests
    steps:
      
      - name: checkout autotests
        uses:  actions/checkout@v5
      - name: setup Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Install dependencies    
        run: pip install -r requirements.txt
      - name: Install Playwright browsers
        run: |
          playwright install
          playwright install-deps
                
     
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results 
        continue-on-error: true
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results  
        continue-on-error: true
      - name: run full tests 
        if: "github.event.inputs.deployment_target == 'full'"
        run: pytest -m full --alluredir=allure-results   
        continue-on-error: true
      - name: run hm tests 
        if: "github.event.inputs.deployment_target == 'hm'"
        run: pytest -m hm --alluredir=allure-results    
        continue-on-error: true
      - name: run slow tests
        if: "github.event.inputs.deployment_target == 'slow'"
        run: pytest -m slow --alluredir=allure-results   
        continue-on-error: true
      - name: run correct tests 
        if: "github.event.inputs.deployment_target == 'correct'"
        run: pytest -m correct --alluredir=allure-results
        continue-on-error: true
      - name: run incorrect tests
        if: "github.event.inputs.deployment_target == 'incorrect'"
        run: pytest -m incorrect --alluredir=allure-results    
        continue-on-error: true


      - name: install Java
        uses: actions/setup-java@v5
        with:
         distribution: 'microsoft' 
         java-version: '17'
      - name: install Allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.tgz && sudo tar -zxvf allure-2.35.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.35.1/bin/allure /usr/bin/allure
      - name: generate report
        run: allure generate -c allure-results -o _site
      - name: save allure report
        uses: actions/upload-artifact@v4    
        with:
          name: _site
          path: _site
          retention-days: 1
 
  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests
    steps: 
      - name: Dowload artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
       
          
