name: SwagLabs tests python

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose test set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - full
          - hm
          - slow
          - correct
          - incorrect
          - all
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run autotests
    steps:
      - name: checkout autotests
        uses:  actions/checkout@v5
      - name: setup Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Install dependencies    
        run: pip install -r requirements.txt
      - name: run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke     
      - name: run full tests
        if: "github.event.inputs.deployment_target == 'full'"
        run: pytest -m full        
      - name: run hm tests
        if: "github.event.inputs.deployment_target == 'hm'"
        run: pytest -m hm     
      - name: run slow tests
        if: "github.event.inputs.deployment_target == 'slow'"
        run: pytest -m slow         
      - name: run correct tests
        if: "github.event.inputs.deployment_target == 'correct'"
        run: pytest -m correct 
      - name: run incorrect tests
        if: "github.event.inputs.deployment_target == 'incorrect'"
        run: pytest -m incorrect        
